version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/vishesh-deepsource/yarr"

[[analyzers]]
name = "test-coverage"